// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Y-ihcueTkoPshxI7CRJFhty49ux9LQQ',
    appId: '1:35274180556:web:f869ca4c385ae823ebff69',
    messagingSenderId: '35274180556',
    projectId: 'teza-8af25',
    authDomain: 'teza-8af25.firebaseapp.com',
    storageBucket: 'teza-8af25.firebasestorage.app',
    measurementId: 'G-LWYLSW46DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31imjPFZDfNaSelcqoW5NhU8PSrU1GQA',
    appId: '1:35274180556:android:866c28e53c6be9d5ebff69',
    messagingSenderId: '35274180556',
    projectId: 'teza-8af25',
    storageBucket: 'teza-8af25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFGmdNSMT4jEbOlEmmWzsKlDw5bDkJ4k',
    appId: '1:35274180556:ios:f0e4e5e549982f36ebff69',
    messagingSenderId: '35274180556',
    projectId: 'teza-8af25',
    storageBucket: 'teza-8af25.firebasestorage.app',
    iosBundleId: 'com.wafula.teza.tezaRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCFGmdNSMT4jEbOlEmmWzsKlDw5bDkJ4k',
    appId: '1:35274180556:ios:f0e4e5e549982f36ebff69',
    messagingSenderId: '35274180556',
    projectId: 'teza-8af25',
    storageBucket: 'teza-8af25.firebasestorage.app',
    iosBundleId: 'com.wafula.teza.tezaRider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Y-ihcueTkoPshxI7CRJFhty49ux9LQQ',
    appId: '1:35274180556:web:9e142c7804cb75f5ebff69',
    messagingSenderId: '35274180556',
    projectId: 'teza-8af25',
    authDomain: 'teza-8af25.firebaseapp.com',
    storageBucket: 'teza-8af25.firebasestorage.app',
    measurementId: 'G-5HQDML3ZNM',
  );
}
